Compiler: slljit::Parser Class Reference
slljit::Parser Class Reference
Used to parse source into AST.
#include <Parser.h>
Public Member Functions
Parser (std::map< char, int > &BinopPrecedence)
void set_source (std::string_view source)
Error set_variables (const Layout &context)
std::pair< list< unique_ptr< PrototypeAST > >, list< unique_ptr< FunctionAST > > > take_ast ()
std::list< std::unique_ptr< FunctionAST > > take_function_ast ()
std::list< std::unique_ptr< PrototypeAST > > take_prototype_ast ()
Error parse ()
void pop_scope ()
void push_scope ()
Error push_var_into_scope (string name, TypeID type)
Expected< TypeID > find_var_in_scope (string name)
void set_current_function_scope (PrototypeAST *p)
const PrototypeAST * get_current_function_scope ()
Protected Member Functions
int getNextToken ()
GetTokPrecedence - Get the precedence of the pending binary operator token.
int GetTokPrecedence ()
Get the precedence of the pending binary operator token.
Expected< std::unique_ptr< ExprAST > > ParseLiteralExpr ()
numberexpr ::= number
Expected< std::unique_ptr< ExprAST > > ParseParenExpr ()
parenexpr ::= '(' expression ')'
Expected< std::unique_ptr< ExprAST > > ParseIdentifierExpr ()
Expected< std::unique_ptr< ExprAST > > ParseIfExpr ()
ifexpr ::= 'if' expression 'then' expression 'else' expression
Expected< std::unique_ptr< ExprAST > > ParseForExpr ()
forexpr ::= 'for' identifier '=' expr ',' expr (',' expr)? 'in' expression
Expected< std::unique_ptr< ExprAST > > ParseVarExpr ()
varexpr ::= 'g_var' identifier ('=' expression)?
Expected< std::unique_ptr< ExprAST > > ParsePrimary ()
Expected< std::unique_ptr< ExprAST > > ParseUnary ()
Expected< std::unique_ptr< ExprAST > > ParseBinOpRHS (int ExprPrec, std::unique_ptr< ExprAST > LHS)
Expected< std::unique_ptr< ExprAST > > ParseExpression ()
Expected< ExprList > ParseExpressionList ()
Expected< std::unique_ptr< PrototypeAST > > ParsePrototype ()
Expected< std::unique_ptr< FunctionAST > > ParseTopLevelTypedExpression ()
definition ::= 'def' prototype expression
Expected< std::unique_ptr< PrototypeAST > > ParseExtern ()
external ::= 'extern' prototype
Error HandleTypedExpression ()
Error HandleExtern ()
Error MainLoop ()
top ::= definition | external | expression | ';'
Protected Attributes
std::map< char, int > & BinopPrecedence
std::list< std::unique_ptr< FunctionAST > > FunctionAST_list
std::list< std::unique_ptr< PrototypeAST > > PrototypeAST_list
std::map< std::string, PrototypeAST & > function_proto_table
PrototypeAST * current_function_proto = nullptr
list< map< string, TypeID > > scope_list
Tokenizer m_tokenizer
int CurTok
Detailed Description
Used to parse source into AST.
Performs Source->Token stream->AST transformation. Keeps track of variable and function scopes.
Constructor & Destructor Documentation
Parser()
slljit::Parser::Parser (std::map< char, int > & BinopPrecedence)
Member Function Documentation
find_var_in_scope()
Expected< TypeID > slljit::Parser::find_var_in_scope (string name) inline
Find variable in scopes by name. Searches scopes retroactively.
Returns
Either error or variable type, requires to be cheked.
References slljit::Tokenizer::get_source_location(), m_tokenizer, and scope_list.
get_current_function_scope()
const PrototypeAST * slljit::Parser::get_current_function_scope ()
Get current function scope.
Returns
prototype AST pointer of current function.
References current_function_proto.
getNextToken()
int slljit::Parser::getNextToken () protected
GetTokPrecedence - Get the precedence of the pending binary operator token.
References CurTok, slljit::Tokenizer::gettok(), and m_tokenizer.
GetTokPrecedence()
int slljit::Parser::GetTokPrecedence () protected
Get the precedence of the pending binary operator token.
References BinopPrecedence, and CurTok.
HandleExtern()
Error slljit::Parser::HandleExtern () protected
References getNextToken(), ParseExtern(), and PrototypeAST_list.
HandleTypedExpression()
Error slljit::Parser::HandleTypedExpression () protected
References FunctionAST_list, getNextToken(), and ParseTopLevelTypedExpression().
MainLoop()
Error slljit::Parser::MainLoop () protected
top ::= definition | external | expression | ';'
References CurTok, slljit::Tokenizer::get_source_location(), getNextToken(), HandleExtern(), HandleTypedExpression(), m_tokenizer, slljit::tok_eof, slljit::tok_extern, and slljit::tok_type.
parse()
Error slljit::Parser::parse ()
Parse the sources.
Returns
Error object, requires to be ckecked.
References MainLoop().
ParseBinOpRHS()
Expected< std::unique_ptr< ExprAST > > slljit::Parser::ParseBinOpRHS (int ExprPrec, std::unique_ptr< ExprAST > LHS) protected
binoprhs ::= ('+' unary)*
References CurTok, getNextToken(), GetTokPrecedence(), ParseBinOpRHS(), and ParseUnary().
ParseExpression()
Expected< std::unique_ptr< ExprAST > > slljit::Parser::ParseExpression () protected
expression ::= unary binoprhs
References CurTok, ParseBinOpRHS(), and ParseUnary().
ParseExpressionList()
Expected< ExprList > slljit::Parser::ParseExpressionList () protected
References CurTok, slljit::Tokenizer::get_source_location(), getNextToken(), m_tokenizer, and ParseExpression().
ParseExtern()
Expected< std::unique_ptr< PrototypeAST > > slljit::Parser::ParseExtern () protected
external ::= 'extern' prototype
References getNextToken(), and ParsePrototype().
ParseForExpr()
Expected< std::unique_ptr< ExprAST > > slljit::Parser::ParseForExpr () protected
forexpr ::= 'for' identifier '=' expr ',' expr (',' expr)? 'in' expression
References CurTok, slljit::Tokenizer::get_source_location(), getNextToken(), m_tokenizer, ParseExpression(), ParseExpressionList(), pop_scope(), and push_scope().
ParseIdentifierExpr()
Expected< std::unique_ptr< ExprAST > > slljit::Parser::ParseIdentifierExpr () protected
identifierexpr ::= identifier ::= identifier '(' expression* ')'
References CurTok, find_var_in_scope(), get_current_function_scope(), slljit::Tokenizer::get_identifier(), slljit::Tokenizer::get_source_location(), getNextToken(), m_tokenizer, slljit::none, ParseExpression(), and PrototypeAST_list.
ParseIfExpr()
Expected< std::unique_ptr< ExprAST > > slljit::Parser::ParseIfExpr () protected
ifexpr ::= 'if' expression 'then' expression 'else' expression
References CurTok, slljit::Tokenizer::get_source_location(), getNextToken(), m_tokenizer, ParseExpression(), ParseExpressionList(), pop_scope(), push_scope(), and slljit::tok_else.
ParseLiteralExpr()
Expected< std::unique_ptr< ExprAST > > slljit::Parser::ParseLiteralExpr () protected
numberexpr ::= number
References slljit::Tokenizer::get_literal_string(), slljit::Tokenizer::get_source_location(), getNextToken(), and m_tokenizer.
ParseParenExpr()
Expected< std::unique_ptr< ExprAST > > slljit::Parser::ParseParenExpr () protected
parenexpr ::= '(' expression ')'
References CurTok, slljit::Tokenizer::get_source_location(), getNextToken(), m_tokenizer, and ParseExpression().
ParsePrimary()
Expected< std::unique_ptr< ExprAST > > slljit::Parser::ParsePrimary () protected
primary ::= identifierexpr ::= numberexpr ::= parenexpr ::= ifexpr ::= forexpr ::= varexpr
References CurTok, slljit::Tokenizer::get_source_location(), m_tokenizer, ParseForExpr(), ParseIdentifierExpr(), ParseIfExpr(), ParseLiteralExpr(), ParseParenExpr(), ParseVarExpr(), slljit::tok_for, slljit::tok_identifier, slljit::tok_if, slljit::tok_literal, and slljit::tok_type.
ParsePrototype()
Expected< std::unique_ptr< PrototypeAST > > slljit::Parser::ParsePrototype () protected
prototype ::= id '(' id* ')' ::= binary LETTER number? (id, id) ::= unary LETTER (id)
References CurTok, slljit::Tokenizer::get_identifier(), slljit::Tokenizer::get_source_location(), slljit::Tokenizer::get_type_identifier(), getNextToken(), m_tokenizer, push_var_into_scope(), slljit::tok_identifier, and slljit::tok_type.
ParseTopLevelTypedExpression()
Expected< std::unique_ptr< FunctionAST > > slljit::Parser::ParseTopLevelTypedExpression () protected
definition ::= 'def' prototype expression
References CurTok, slljit::Tokenizer::get_source_location(), m_tokenizer, ParseExpressionList(), ParsePrototype(), pop_scope(), PrototypeAST_list, push_scope(), set_current_function_scope(), and slljit::tok_type.
ParseUnary()
Expected< std::unique_ptr< ExprAST > > slljit::Parser::ParseUnary () protected
unary ::= primary ::= '!' unary
References CurTok, getNextToken(), ParsePrimary(), and ParseUnary().
ParseVarExpr()
Expected< std::unique_ptr< ExprAST > > slljit::Parser::ParseVarExpr () protected
varexpr ::= 'g_var' identifier ('=' expression)?
References CurTok, slljit::Tokenizer::get_identifier(), slljit::Tokenizer::get_source_location(), slljit::Tokenizer::get_type_identifier(), getNextToken(), m_tokenizer, ParseExpression(), push_var_into_scope(), and slljit::tok_identifier.
pop_scope()
void slljit::Parser::pop_scope () inline
Pop current variable scope from stack.
References scope_list.
push_scope()
void slljit::Parser::push_scope () inline
Puch empty variable scope to stack.
References scope_list.
push_var_into_scope()
Error slljit::Parser::push_var_into_scope (string name, TypeID type) inline
Puch variable into current scope.
References slljit::Tokenizer::get_source_location(), m_tokenizer, and scope_list.
set_current_function_scope()
void slljit::Parser::set_current_function_scope (PrototypeAST * p)
Set current function scope.
Parameters
p ptotoype AST pointer.
References current_function_proto.
set_source()
void slljit::Parser::set_source (std::string_view source)
Sets source to process.
Parameters
source Source program string.
References getNextToken(), m_tokenizer, and slljit::Tokenizer::set_source().
set_variables()
Error slljit::Parser::set_variables (const Layout & context)
Sets Layout variables to use as a reference during parse process.
Parameters
context Reference to Layout to take variables from.
References slljit::Layout::constant_globals, slljit::Layout::globals, push_scope(), and push_var_into_scope().
take_ast()
std::pair< list< unique_ptr< PrototypeAST > >, list< unique_ptr< FunctionAST > > > slljit::Parser::take_ast ()
Take posession of parsed AST.
Returns
Moved pair of lists of prototypes and function AST expressions.
References FunctionAST_list, and PrototypeAST_list.
take_function_ast()
std::list< std::unique_ptr< FunctionAST > > slljit::Parser::take_function_ast ()
Take posession of functions AST.
Returns
Moved list of functions AST
References FunctionAST_list.
take_prototype_ast()
std::list< std::unique_ptr< PrototypeAST > > slljit::Parser::take_prototype_ast ()
Take posession of function prototypes AST.
Returns
Moved list of function prototypes AST.
References PrototypeAST_list.
Member Data Documentation
BinopPrecedence
std::map<char, int>& slljit::Parser::BinopPrecedence protected
current_function_proto
PrototypeAST* slljit::Parser::current_function_proto = nullptr protected
CurTok
int slljit::Parser::CurTok protected
CurTok/getNextToken - Provide a simple token buffer. CurTok is the current token the parser is looking at. getNextToken reads another token from the lexer and updates CurTok with its results.
function_proto_table
std::map<std::string, PrototypeAST&> slljit::Parser::function_proto_table protected
FunctionAST_list
std::list<std::unique_ptr<FunctionAST> > slljit::Parser::FunctionAST_list protected
m_tokenizer
Tokenizer slljit::Parser::m_tokenizer protected
PrototypeAST_list
std::list<std::unique_ptr<PrototypeAST> > slljit::Parser::PrototypeAST_list protected
scope_list
list<map<string, TypeID> > slljit::Parser::scope_list protected
The documentation for this class was generated from the following files:
src/include/Parser.h
src/Parser.cpp