Compiler: slljit::CodeGen Class Reference
slljit::CodeGen Class Reference
#include <CodeGen.h>
Public Member Functions
void compile_layout (Context &m_context, LocalContext &m_local_context)
Error compile (std::list< std::unique_ptr< PrototypeAST > > prototypes, std::list< std::unique_ptr< FunctionAST > > functions, Context &m_context, LocalContext &m_local_context, CompileOptions &options, bool bDumpIR=false)
Member Function Documentation
compile()
Error slljit::CodeGen::compile (std::list< std::unique_ptr< PrototypeAST > > prototypes, std::list< std::unique_ptr< FunctionAST > > functions, Context & m_context, LocalContext & m_local_context, CompileOptions & options, bool bDumpIR = false)
References slljit::LocalContext::FunctionProtos, slljit::LocalContext::getJITDylib(), slljit::LocalContext::getModule(), slljit::CompileOptions::O0, slljit::CompileOptions::opt_level, slljit::Context::shllJIT, slljit::LocalContext::takeContext(), slljit::LocalContext::takeModule(), and slljit::CompileOptions::to_llvm_opt_level().
compile_layout()
void slljit::CodeGen::compile_layout (Context & m_context, LocalContext & m_local_context)
References slljit::get_llvm_type(), slljit::LocalContext::getBuilder(), slljit::LocalContext::getContext(), slljit::LocalContext::getLayout(), and slljit::LocalContext::getModule().
The documentation for this class was generated from the following files:
src/include/CodeGen.h
src/CodeGen.cpp