Compiler: slljit::Program< T, R > Class Template Reference
slljit::Program< T, R > Class Template Reference
Used to compile, hold and run a shader program.
#include <Program.hpp>
Public Member Functions
Program (Context &m_context, Layout layout, const string body)
Error compile (CompileOptions options=CompileOptions(), bool bDumpIR=false)
R run (T *data)
Private Attributes
Context & m_context
LocalContext m_local_context
const string m_body
R(* main_func)(T *) = nullptr
Detailed Description
template<class T, typename R>
class slljit::Program< T, R >
Used to compile, hold and run a shader program.
Thread-safe for compilation.
Template Parameters
T data structure type used to pass data to compiled function
R compiled function return type
Constructor & Destructor Documentation
Program()
template<class T , typename R > slljit::Program< T, R >::Program (Context & m_context, Layout layout, const string body) inline
Program constructor
Parameters
m_context global context to use
layout Layout to use
body source code string
Member Function Documentation
compile()
template<class T , typename R > Error slljit::Program< T, R >::compile (CompileOptions options = CompileOptions(), bool bDumpIR = false) inline
Compiles source to binary if not already compiled. No recompilation occurs if different parameters are passed but Program is already compiled. Thread-safe.
Parameters
options CompileOptions to use for compilation.
bDumpIR If ir should be dumped to console during compilation. Not threadsafe.
Returns
Error object, requires to be checked.
References slljit::LocalContext::BinopPrecedence, slljit::CodeGen::compile(), slljit::CodeGen::compile_layout(), slljit::LocalContext::getJITDylib(), slljit::LocalContext::getLayout(), slljit::Program< T, R >::m_body, slljit::Program< T, R >::m_context, slljit::Program< T, R >::m_local_context, slljit::Program< T, R >::main_func, slljit::Parser::parse(), slljit::Parser::set_source(), slljit::Parser::set_variables(), slljit::Context::shllJIT, and slljit::Parser::take_ast().
run()
template<class T , typename R > R slljit::Program< T, R >::run (T * data) inline
Run compiled function with provided data object pointer.
Parameters
data Pointer to the data object.
Returns
Passthrough value from compiled function.
References slljit::Program< T, R >::main_func.
Member Data Documentation
m_body
template<class T , typename R > const string slljit::Program< T, R >::m_body private
m_context
template<class T , typename R > Context& slljit::Program< T, R >::m_context private
m_local_context
template<class T , typename R > LocalContext slljit::Program< T, R >::m_local_context private
main_func
template<class T , typename R > R(* slljit::Program< T, R >::main_func) (T *) = nullptr private
The documentation for this class was generated from the following file:
src/include/Program.hpp