Compiler: slljit::BinaryExprAST Class Reference
slljit::BinaryExprAST Class Reference
The AST Class Group
Expression class for a binary operator.
#include <AST.h>
Public Member Functions
BinaryExprAST (char Op, std::unique_ptr< ExprAST > LHS, std::unique_ptr< ExprAST > RHS)
Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context) override
Public Member Functions inherited from slljit::ExprAST
ExprAST ()=default
ExprAST (TypeID type_)
virtual TypeID getType () const
virtual TypeID getRetType () const
virtual ~ExprAST ()=default
virtual bool bExpectSemicolon ()
virtual bool bIsNoOp ()
virtual bool bIsTerminator ()
virtual Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context)=0
Private Attributes
char Op
std::unique_ptr< ExprAST > LHS
std::unique_ptr< ExprAST > RHS
Additional Inherited Members
Public Attributes inherited from slljit::ExprAST
TypeID type_ = none
Detailed Description
Expression class for a binary operator.
Constructor & Destructor Documentation
BinaryExprAST()
slljit::BinaryExprAST::BinaryExprAST (char Op, std::unique_ptr< ExprAST > LHS, std::unique_ptr< ExprAST > RHS) inline
References slljit::ExprAST::type_.
Member Function Documentation
codegen()
Expected< Value * > slljit::BinaryExprAST::codegen (Context & m_context, LocalContext & m_local_context) override virtual
Implements slljit::ExprAST.
References slljit::boolTyID, slljit::CreateAdd(), slljit::CreateDiv(), slljit::CreateExplictCast(), slljit::CreateImplictCast(), slljit::CreateMul(), slljit::CreateSub(), slljit::CtreateCMP(), slljit::LocalContext::find_var_in_scope(), slljit::LocalContext::getBuilder(), slljit::LocalContext::getContext(), slljit::getFunction(), slljit::LocalContext::getModule(), slljit::VariableExprAST::getName(), slljit::ExprAST::getType(), slljit::greater_than, slljit::less_then, LHS, Op, RHS, and slljit::ExprAST::type_.
Member Data Documentation
LHS
std::unique_ptr<ExprAST> slljit::BinaryExprAST::LHS private
Op
char slljit::BinaryExprAST::Op private
RHS
std::unique_ptr<ExprAST> slljit::BinaryExprAST::RHS private
The documentation for this class was generated from the following files:
src/include/AST.h
src/AST.cpp