Compiler: slljit::PrototypeAST Class Reference
slljit::PrototypeAST Class Reference
The AST Class Group
Expression class for function prototypes.
#include <AST.h>
Public Member Functions
PrototypeAST (TypeID ret_type_, const std::string &Name, std::vector< TypeID > ArgTypes, std::vector< std::string > Args, bool IsOperator=false, unsigned Prec=0)
Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context) override
TypeID getRetType () const override
std::vector< TypeID > getArgTypes () const
bool isMain () const
bool match (string name) const
const std::string & getName () const
bool isUnaryOp () const
bool isBinaryOp () const
char getOperatorName () const
unsigned getBinaryPrecedence () const
Public Member Functions inherited from slljit::ExprAST
ExprAST ()=default
ExprAST (TypeID type_)
virtual TypeID getType () const
virtual TypeID getRetType () const
virtual ~ExprAST ()=default
virtual bool bExpectSemicolon ()
virtual bool bIsNoOp ()
virtual bool bIsTerminator ()
virtual Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context)=0
Private Attributes
const std::string Name
const std::vector< std::string > Args
const std::vector< TypeID > ArgTypes
const TypeID ret_type_
const bool IsOperator
const unsigned Precedence
Additional Inherited Members
Public Attributes inherited from slljit::ExprAST
TypeID type_ = none
Detailed Description
Expression class for function prototypes.
This class represents the "prototype" for a function, which captures its name, and its argument names (thus implicitly the number of arguments the function takes), as well as if it is an operator.
Constructor & Destructor Documentation
PrototypeAST()
slljit::PrototypeAST::PrototypeAST (TypeID ret_type_, const std::string & Name, std::vector< TypeID > ArgTypes, std::vector< std::string > Args, bool IsOperator = false, unsigned Prec = 0) inline
Member Function Documentation
codegen()
Expected< Value * > slljit::PrototypeAST::codegen (Context & m_context, LocalContext & m_local_context) override virtual
Implements slljit::ExprAST.
References Args, ArgTypes, slljit::get_llvm_type(), slljit::LocalContext::getContext(), slljit::LocalContext::getLayout(), slljit::LocalContext::getModule(), isMain(), Name, ret_type_, and slljit::ExprAST::type_.
getArgTypes()
std::vector< TypeID > slljit::PrototypeAST::getArgTypes () const
References ArgTypes.
getBinaryPrecedence()
unsigned slljit::PrototypeAST::getBinaryPrecedence () const
References Precedence.
getName()
const std::string & slljit::PrototypeAST::getName () const
References Name.
getOperatorName()
char slljit::PrototypeAST::getOperatorName () const
References isBinaryOp(), isUnaryOp(), and Name.
getRetType()
TypeID slljit::PrototypeAST::getRetType () const override virtual
Reimplemented from slljit::ExprAST.
References ret_type_.
isBinaryOp()
bool slljit::PrototypeAST::isBinaryOp () const
References Args, and IsOperator.
isMain()
bool slljit::PrototypeAST::isMain () const
References Name.
isUnaryOp()
bool slljit::PrototypeAST::isUnaryOp () const
References Args, and IsOperator.
match()
bool slljit::PrototypeAST::match (string name) const
References Name.
Member Data Documentation
Args
const std::vector<std::string> slljit::PrototypeAST::Args private
ArgTypes
const std::vector<TypeID> slljit::PrototypeAST::ArgTypes private
IsOperator
const bool slljit::PrototypeAST::IsOperator private
Name
const std::string slljit::PrototypeAST::Name private
Precedence
const unsigned slljit::PrototypeAST::Precedence private
ret_type_
const TypeID slljit::PrototypeAST::ret_type_ private
The documentation for this class was generated from the following files:
src/include/AST.h
src/AST.cpp