Compiler: slljit::IfExprAST Class Reference
slljit::IfExprAST Class Reference
The AST Class Group
Expression class for if/else.
#include <AST.h>
Public Member Functions
IfExprAST (std::unique_ptr< ExprAST > Cond, ExprList Then, ExprList Else)
bool bExpectSemicolon () override
Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context) override
Public Member Functions inherited from slljit::ExprAST
ExprAST ()=default
ExprAST (TypeID type_)
virtual TypeID getType () const
virtual TypeID getRetType () const
virtual ~ExprAST ()=default
virtual bool bExpectSemicolon ()
virtual bool bIsNoOp ()
virtual bool bIsTerminator ()
virtual Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context)=0
Private Attributes
std::unique_ptr< ExprAST > Cond
ExprList Then
ExprList Else
Additional Inherited Members
Public Attributes inherited from slljit::ExprAST
TypeID type_ = none
Detailed Description
Expression class for if/else.
Constructor & Destructor Documentation
IfExprAST()
slljit::IfExprAST::IfExprAST (std::unique_ptr< ExprAST > Cond, ExprList Then, ExprList Else) inline
Member Function Documentation
bExpectSemicolon()
bool slljit::IfExprAST::bExpectSemicolon () inline override virtual
Reimplemented from slljit::ExprAST.
codegen()
Expected< Value * > slljit::IfExprAST::codegen (Context & m_context, LocalContext & m_local_context) override virtual
Implements slljit::ExprAST.
References slljit::boolTyID, Cond, slljit::CreateExplictCast(), Else, slljit::LocalContext::getBuilder(), slljit::LocalContext::getContext(), slljit::LocalContext::pop_scope(), slljit::LocalContext::push_scope(), and Then.
Member Data Documentation
Cond
std::unique_ptr<ExprAST> slljit::IfExprAST::Cond private
Else
ExprList slljit::IfExprAST::Else private
Then
ExprList slljit::IfExprAST::Then private
The documentation for this class was generated from the following files:
src/include/AST.h
src/AST.cpp