Compiler: slljit::CallExprAST Class Reference
slljit::CallExprAST Class Reference
The AST Class Group
Expression class for function calls.
#include <AST.h>
Public Member Functions
CallExprAST (TypeID ret_type_, const std::string &Callee, std::vector< TypeID > ArgTypes, std::vector< std::unique_ptr< ExprAST > > Args)
Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context) override
Public Member Functions inherited from slljit::ExprAST
ExprAST ()=default
ExprAST (TypeID type_)
virtual TypeID getType () const
virtual TypeID getRetType () const
virtual ~ExprAST ()=default
virtual bool bExpectSemicolon ()
virtual bool bIsNoOp ()
virtual bool bIsTerminator ()
virtual Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context)=0
Private Attributes
std::string Callee
std::vector< std::unique_ptr< ExprAST > > Args
std::vector< TypeID > ArgTypes
Additional Inherited Members
Public Attributes inherited from slljit::ExprAST
TypeID type_ = none
Detailed Description
Expression class for function calls.
Constructor & Destructor Documentation
CallExprAST()
slljit::CallExprAST::CallExprAST (TypeID ret_type_, const std::string & Callee, std::vector< TypeID > ArgTypes, std::vector< std::unique_ptr< ExprAST > > Args) inline
Member Function Documentation
codegen()
Expected< Value * > slljit::CallExprAST::codegen (Context & m_context, LocalContext & m_local_context) override virtual
Implements slljit::ExprAST.
References Args, ArgTypes, Callee, slljit::CreateExplictCast(), slljit::LocalContext::getBuilder(), and slljit::getFunction().
Member Data Documentation
Args
std::vector<std::unique_ptr<ExprAST> > slljit::CallExprAST::Args private
ArgTypes
std::vector<TypeID> slljit::CallExprAST::ArgTypes private
Callee
std::string slljit::CallExprAST::Callee private
The documentation for this class was generated from the following files:
src/include/AST.h
src/AST.cpp