Compiler: slljit::NumberExprAST Class Reference
slljit::NumberExprAST Class Reference
The AST Class Group
Expression class for numeric literals like "1.0".
#include <AST.h>
Public Member Functions
NumberExprAST (bool Val)
NumberExprAST (double Val)
NumberExprAST (int64_t Val)
Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context) override
Public Member Functions inherited from slljit::ExprAST
ExprAST ()=default
ExprAST (TypeID type_)
virtual TypeID getType () const
virtual TypeID getRetType () const
virtual ~ExprAST ()=default
virtual bool bExpectSemicolon ()
virtual bool bIsNoOp ()
virtual bool bIsTerminator ()
virtual Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context)=0
Private Attributes
union {
bool ValB
double ValD
int64_t ValSI64
};
Additional Inherited Members
Public Attributes inherited from slljit::ExprAST
TypeID type_ = none
Detailed Description
Expression class for numeric literals like "1.0".
Constructor & Destructor Documentation
NumberExprAST() [1/3]
slljit::NumberExprAST::NumberExprAST (bool Val) inline
NumberExprAST() [2/3]
slljit::NumberExprAST::NumberExprAST (double Val) inline
NumberExprAST() [3/3]
slljit::NumberExprAST::NumberExprAST (int64_t Val) inline
Member Function Documentation
codegen()
Expected< Value * > slljit::NumberExprAST::codegen (Context & m_context, LocalContext & m_local_context) override virtual
Implements slljit::ExprAST.
References slljit::boolTyID, slljit::doubleTyID, slljit::get_llvm_type(), slljit::LocalContext::getContext(), slljit::int64TyID, slljit::isSigned(), slljit::ExprAST::type_, ValB, ValD, and ValSI64.
Member Data Documentation
union { ... } slljit::NumberExprAST::@3
ValB
bool slljit::NumberExprAST::ValB
ValD
double slljit::NumberExprAST::ValD
ValSI64
int64_t slljit::NumberExprAST::ValSI64
The documentation for this class was generated from the following files:
src/include/AST.h
src/AST.cpp