Compiler: slljit::Tokenizer Class Reference
slljit::Tokenizer Class Reference
Used to transform source into token stream.
#include <Tokenizer.h>
Public Member Functions
void set_source (std::string_view source)
int gettok ()
std::pair< size_t, size_t > get_source_location () const
std::string get_identifier ()
std::string get_type_identifier ()
std::string get_literal_string ()
Protected Member Functions
int _getchar ()
void set_lok_location ()
Static Protected Member Functions
static bool is_special_literal (string c)
static pair< bool, Token > is_reserved_command_id (string c)
static bool is_id_start_char (int c)
static bool is_id_char (int c)
Protected Attributes
std::string IdentifierStr
std::string TypeIdentifierStr
std::string LiteralStr
std::string_view source_code
size_t source_idx = 0
size_t line_count = 1
size_t line_char_count = 0
pair< size_t, size_t > tok_location = {-1, -1}
int LastChar = ' '
Static Protected Attributes
static const set< char > identifier_start_charset
static const set< char > identifier_charset
static const map< string, Token > reserved_identifier_set = {{"extern", tok_extern}, {"if", tok_if}, {"else", tok_else}, {"for", tok_for}}
Detailed Description
Used to transform source into token stream.
Keeps immediate token location and defining data.
Member Function Documentation
_getchar()
int slljit::Tokenizer::_getchar () inline protected
References line_char_count, line_count, source_code, and source_idx.
get_identifier()
std::string slljit::Tokenizer::get_identifier ()
References IdentifierStr.
get_literal_string()
std::string slljit::Tokenizer::get_literal_string ()
References LiteralStr.
get_source_location()
std::pair< size_t, size_t > slljit::Tokenizer::get_source_location () const
Return current token location in source.
Returns
Line and character number in the line. 1 based counting.
References tok_location.
get_type_identifier()
std::string slljit::Tokenizer::get_type_identifier ()
References TypeIdentifierStr.
gettok()
int slljit::Tokenizer::gettok ()
Get next token from source code.
Returns
an integer representation of a token. Either a Token or a character. slljit::Token
References _getchar(), gettok(), IdentifierStr, is_id_char(), is_id_start_char(), is_reserved_command_id(), is_special_literal(), LastChar, LiteralStr, set_lok_location(), slljit::tok_eof, slljit::tok_identifier, slljit::tok_literal, slljit::tok_type, and TypeIdentifierStr.
is_id_char()
bool slljit::Tokenizer::is_id_char (int c) inline static protected
References identifier_charset.
is_id_start_char()
bool slljit::Tokenizer::is_id_start_char (int c) inline static protected
References identifier_start_charset.
is_reserved_command_id()
pair< bool, Token > slljit::Tokenizer::is_reserved_command_id (string c) inline static protected
References reserved_identifier_set, and slljit::tok_eof.
is_special_literal()
bool slljit::Tokenizer::is_special_literal (string c) inline static protected
References slljit::special_literals.
set_lok_location()
void slljit::Tokenizer::set_lok_location () inline protected
References line_char_count, line_count, and tok_location.
set_source()
void slljit::Tokenizer::set_source (std::string_view source)
Sets source to process.
Parameters
source Source program string.
References source_code.
Member Data Documentation
identifier_charset
const set< char > slljit::Tokenizer::identifier_charset static protected
Initial value:
= {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D',
        'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '_'}
identifier_start_charset
const set< char > slljit::Tokenizer::identifier_start_charset static protected
Initial value:
= {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C',
        'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '_'}
IdentifierStr
std::string slljit::Tokenizer::IdentifierStr protected
LastChar
int slljit::Tokenizer::LastChar = ' ' protected
line_char_count
size_t slljit::Tokenizer::line_char_count = 0 protected
line_count
size_t slljit::Tokenizer::line_count = 1 protected
LiteralStr
std::string slljit::Tokenizer::LiteralStr protected
reserved_identifier_set
const map< string, Token > slljit::Tokenizer::reserved_identifier_set = {{"extern", tok_extern}, {"if", tok_if}, {"else", tok_else}, {"for", tok_for}} static protected
source_code
std::string_view slljit::Tokenizer::source_code protected
source_idx
size_t slljit::Tokenizer::source_idx = 0 protected
tok_location
pair<size_t, size_t> slljit::Tokenizer::tok_location = {-1, -1} protected
TypeIdentifierStr
std::string slljit::Tokenizer::TypeIdentifierStr protected
The documentation for this class was generated from the following files:
src/include/Tokenizer.h
src/Tokenizer.cpp