Compiler: slljit::ReturnExprAST Class Reference
slljit::ReturnExprAST Class Reference
The AST Class Group
Expression class for a unary operator.
#include <AST.h>
Public Member Functions
ReturnExprAST (std::unique_ptr< ExprAST > Operand, TypeID type_)
virtual bool bIsTerminator () override
Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context) override
Public Member Functions inherited from slljit::ExprAST
ExprAST ()=default
ExprAST (TypeID type_)
virtual TypeID getType () const
virtual TypeID getRetType () const
virtual ~ExprAST ()=default
virtual bool bExpectSemicolon ()
virtual bool bIsNoOp ()
virtual bool bIsTerminator ()
virtual Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context)=0
Private Attributes
std::unique_ptr< ExprAST > Operand
Additional Inherited Members
Public Attributes inherited from slljit::ExprAST
TypeID type_ = none
Detailed Description
Expression class for a unary operator.
Constructor & Destructor Documentation
ReturnExprAST()
slljit::ReturnExprAST::ReturnExprAST (std::unique_ptr< ExprAST > Operand, TypeID type_) inline
Member Function Documentation
bIsTerminator()
virtual bool slljit::ReturnExprAST::bIsTerminator () inline override virtual
Reimplemented from slljit::ExprAST.
codegen()
Expected< Value * > slljit::ReturnExprAST::codegen (Context & m_context, LocalContext & m_local_context) override virtual
Implements slljit::ExprAST.
References slljit::CreateExplictCast(), slljit::LocalContext::getBuilder(), slljit::ExprAST::getType(), and Operand.
Member Data Documentation
Operand
std::unique_ptr<ExprAST> slljit::ReturnExprAST::Operand private
The documentation for this class was generated from the following files:
src/include/AST.h
src/AST.cpp