Compiler: slljit::VarExprAST Class Reference
slljit::VarExprAST Class Reference
The AST Class Group
Expression class for g_var/in.
#include <AST.h>
Public Member Functions
VarExprAST (TypeID VarType, std::vector< std::pair< std::string, std::unique_ptr< ExprAST > > > VarNames)
Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context) override
Public Member Functions inherited from slljit::ExprAST
ExprAST ()=default
ExprAST (TypeID type_)
virtual TypeID getType () const
virtual TypeID getRetType () const
virtual ~ExprAST ()=default
virtual bool bExpectSemicolon ()
virtual bool bIsNoOp ()
virtual bool bIsTerminator ()
virtual Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context)=0
Private Attributes
std::vector< std::pair< std::string, std::unique_ptr< ExprAST > > > VarNames
Additional Inherited Members
Public Attributes inherited from slljit::ExprAST
TypeID type_ = none
Detailed Description
Expression class for g_var/in.
Constructor & Destructor Documentation
VarExprAST()
slljit::VarExprAST::VarExprAST (TypeID VarType, std::vector< std::pair< std::string, std::unique_ptr< ExprAST > > > VarNames) inline
Member Function Documentation
codegen()
Expected< Value * > slljit::VarExprAST::codegen (Context & m_context, LocalContext & m_local_context) override virtual
Implements slljit::ExprAST.
References slljit::LocalContext::check_curent_scope(), slljit::ExprAST::codegen(), slljit::CreateEntryBlockAlloca(), slljit::CreateExplictCast(), slljit::doubleTyID, slljit::LocalContext::getBuilder(), slljit::LocalContext::getContext(), slljit::ExprAST::getType(), slljit::none, slljit::LocalContext::push_var_into_scope(), slljit::ExprAST::type_, and VarNames.
Member Data Documentation
VarNames
std::vector<std::pair<std::string, std::unique_ptr<ExprAST> > > slljit::VarExprAST::VarNames private
The documentation for this class was generated from the following files:
src/include/AST.h
src/AST.cpp