Compiler: slljit::FunctionAST Class Reference
slljit::FunctionAST Class Reference
The AST Class Group
This class represents a function definition itself.
#include <AST.h>
Public Member Functions
FunctionAST (PrototypeAST &Proto, ExprList Body)
Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context) override
TypeID getRetType () const override
const std::string & getName () const
bool isMain () const
Public Member Functions inherited from slljit::ExprAST
ExprAST ()=default
ExprAST (TypeID type_)
virtual TypeID getType () const
virtual TypeID getRetType () const
virtual ~ExprAST ()=default
virtual bool bExpectSemicolon ()
virtual bool bIsNoOp ()
virtual bool bIsTerminator ()
virtual Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context)=0
Private Attributes
PrototypeAST & Proto
ExprList Body
Additional Inherited Members
Public Attributes inherited from slljit::ExprAST
TypeID type_ = none
Detailed Description
This class represents a function definition itself.
Constructor & Destructor Documentation
FunctionAST()
slljit::FunctionAST::FunctionAST (PrototypeAST & Proto, ExprList Body) inline
Member Function Documentation
codegen()
Expected< Value * > slljit::FunctionAST::codegen (Context & m_context, LocalContext & m_local_context) override virtual
Implements slljit::ExprAST.
References slljit::LocalContext::BinopPrecedence, Body, slljit::CreateEntryBlockAlloca(), slljit::PrototypeAST::getBinaryPrecedence(), slljit::LocalContext::getBuilder(), slljit::LocalContext::getContext(), slljit::getFunction(), slljit::LocalContext::getLayout(), slljit::LocalContext::getModule(), slljit::PrototypeAST::getName(), slljit::PrototypeAST::getOperatorName(), slljit::PrototypeAST::isBinaryOp(), isMain(), slljit::LocalContext::pop_scope(), Proto, slljit::LocalContext::push_scope(), and slljit::LocalContext::push_var_into_scope().
getName()
const std::string & slljit::FunctionAST::getName () const
References slljit::PrototypeAST::getName(), and Proto.
getRetType()
TypeID slljit::FunctionAST::getRetType () const inline override virtual
Reimplemented from slljit::ExprAST.
References slljit::PrototypeAST::getRetType(), and Proto.
isMain()
bool slljit::FunctionAST::isMain () const
References slljit::PrototypeAST::isMain(), and Proto.
Member Data Documentation
Body
ExprList slljit::FunctionAST::Body private
Proto
PrototypeAST& slljit::FunctionAST::Proto private
The documentation for this class was generated from the following files:
src/include/AST.h
src/AST.cpp