Compiler: slljit::VariableExprAST Class Reference
slljit::VariableExprAST Class Reference
The AST Class Group
Expression class for referencing a variable, like "a".
#include <AST.h>
Public Member Functions
VariableExprAST (const std::string &Name, TypeID type_)
Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context) override
const std::string & getName () const
Public Member Functions inherited from slljit::ExprAST
ExprAST ()=default
ExprAST (TypeID type_)
virtual TypeID getType () const
virtual TypeID getRetType () const
virtual ~ExprAST ()=default
virtual bool bExpectSemicolon ()
virtual bool bIsNoOp ()
virtual bool bIsTerminator ()
virtual Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context)=0
Private Attributes
std::string Name
Additional Inherited Members
Public Attributes inherited from slljit::ExprAST
TypeID type_ = none
Detailed Description
Expression class for referencing a variable, like "a".
Constructor & Destructor Documentation
VariableExprAST()
slljit::VariableExprAST::VariableExprAST (const std::string & Name, TypeID type_) inline
Member Function Documentation
codegen()
Expected< Value * > slljit::VariableExprAST::codegen (Context & m_context, LocalContext & m_local_context) override virtual
Implements slljit::ExprAST.
References slljit::LocalContext::find_var_in_scope(), slljit::LocalContext::getBuilder(), slljit::LocalContext::getModule(), and Name.
getName()
const std::string & slljit::VariableExprAST::getName () const inline
References Name.
Member Data Documentation
Name
std::string slljit::VariableExprAST::Name private
The documentation for this class was generated from the following files:
src/include/AST.h
src/AST.cpp