Compiler: slljit::ForExprAST Class Reference
slljit::ForExprAST Class Reference
The AST Class Group
Expression class for for/in.
#include <AST.h>
Public Member Functions
ForExprAST (std::unique_ptr< ExprAST > VarInit, std::unique_ptr< ExprAST > Cond, ExprList Body, std::unique_ptr< ExprAST > EndExpr)
bool bExpectSemicolon () override
Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context) override
Public Member Functions inherited from slljit::ExprAST
ExprAST ()=default
ExprAST (TypeID type_)
virtual TypeID getType () const
virtual TypeID getRetType () const
virtual ~ExprAST ()=default
virtual bool bExpectSemicolon ()
virtual bool bIsNoOp ()
virtual bool bIsTerminator ()
virtual Expected< Value * > codegen (Context &m_context, LocalContext &m_local_context)=0
Private Attributes
std::unique_ptr< ExprAST > VarInit
std::unique_ptr< ExprAST > Cond
ExprList Body
std::unique_ptr< ExprAST > EndExpr
Additional Inherited Members
Public Attributes inherited from slljit::ExprAST
TypeID type_ = none
Detailed Description
Expression class for for/in.
Constructor & Destructor Documentation
ForExprAST()
slljit::ForExprAST::ForExprAST (std::unique_ptr< ExprAST > VarInit, std::unique_ptr< ExprAST > Cond, ExprList Body, std::unique_ptr< ExprAST > EndExpr) inline
Member Function Documentation
bExpectSemicolon()
bool slljit::ForExprAST::bExpectSemicolon () inline override virtual
Reimplemented from slljit::ExprAST.
codegen()
Expected< Value * > slljit::ForExprAST::codegen (Context & m_context, LocalContext & m_local_context) override virtual
Implements slljit::ExprAST.
References Body, slljit::boolTyID, Cond, slljit::CreateExplictCast(), EndExpr, slljit::LocalContext::getBuilder(), slljit::LocalContext::getContext(), slljit::LocalContext::pop_scope(), slljit::LocalContext::push_scope(), and VarInit.
Member Data Documentation
Body
ExprList slljit::ForExprAST::Body private
Cond
std::unique_ptr<ExprAST> slljit::ForExprAST::Cond private
EndExpr
std::unique_ptr<ExprAST> slljit::ForExprAST::EndExpr private
VarInit
std::unique_ptr<ExprAST> slljit::ForExprAST::VarInit private
The documentation for this class was generated from the following files:
src/include/AST.h
src/AST.cpp