Compiler: src/compiler_cli.cpp File Reference
compiler_cli.cpp File Reference
#include "pch.h"
#include "Tokenizer.h"
#include "Context.h"
#include "Layout.h"
#include "Program.hpp"
#include <taskflow/taskflow.hpp>
#include <sstream>
#include <iomanip>
#include <iostream>
Classes
struct Data
Namespaces
namespace slljit
Macros
#define DLLEXPORT
Functions
DLLEXPORT double putchard (double X)
putchard - putchar that takes a double and returns 0.
DLLEXPORT double printd (double X)
printd - printf that takes a double prints it as "%f\n", returning 0.
std::string hexStr (unsigned char *data, int len)
int main (int argc, char **argv)
Variables
const std::string source_code
Macro Definition Documentation
DLLEXPORT
#define DLLEXPORT
Function Documentation
hexStr()
std::string hexStr (unsigned char * data, int len)
main()
int main (int argc, char ** argv)
References slljit::Layout::addMember(), slljit::Program< T, R >::compile(), slljit::Kdouble, slljit::Program< T, R >::run(), and source_code.
printd()
DLLEXPORT double printd (double X)
printd - printf that takes a double prints it as "%f\n", returning 0.
putchard()
DLLEXPORT double putchard (double X)
putchard - putchar that takes a double and returns 0.
Variable Documentation
source_code
const std::string source_code
Initial value:
= R"(
uint64 main()
{
    double left = start_0;
    double right = start_1;
    for(int64 idx = 0; idx < iter - 1; idx = idx + 1)
    {
        double tmp = right + left;
        left = right;
        right = tmp;
    }
    uint64 result = right;
    return result;
}
)"