Compiler: slljit Namespace Reference
slljit Namespace Reference
Classes
class BinaryExprAST
Expression class for a binary operator.
class CallExprAST
Expression class for function calls.
class CodeGen
class CompileError
Used to repseresnt CodeGen and compile() errors.
struct CompileOptions
Used to pass parameters to code generation stage.
struct ConstantGlobalDefinition
class Context
Used to hold global compilation and execution context.
class DummyCache
class ExprAST
Base class for all expression nodes.
class ForExprAST
Expression class for for/in.
class FunctionAST
This class represents a function definition itself.
struct GlobalDefinition
class IfExprAST
Expression class for if/else.
class Layout
class LocalContext
Used to define context for a single Program.
class NoOpAST
Expression class to represent NoOp.
class NumberExprAST
Expression class for numeric literals like "1.0".
class Parser
Used to parse source into AST.
class ParserError
Used to represent Parser errors.
class Program
Used to compile, hold and run a shader program.
class PrototypeAST
Expression class for function prototypes.
class ReturnExprAST
Expression class for a unary operator.
class ShaderJIT
class Tokenizer
Used to transform source into token stream.
class UnaryExprAST
Expression class for a unary operator.
class VarExprAST
Expression class for g_var/in.
class VariableExprAST
Expression class for referencing a variable, like "a".
Concepts
concept BasicType
Typedefs
typedef std::list< std::unique_ptr< ExprAST > > ExprList
Enumerations
enum CmpPredicate {
equal , not_equal , greater_than , greater_or_equal ,
less_then , less_or_equal
}
CmpPredicate enum.
enum LayoutVarTypes { Kdouble = doubleTyID , Kint64 = int64TyID , Kuint64 = uint64TyID }
enum Token : int {
tok_eof = -1 , tok_type = -2 , tok_extern = -3 , tok_identifier = -4 ,
tok_literal = -5 , tok_if = -6 , tok_else = -8 , tok_for = -9
}
Token enum.
enum TypeID {
boolTyID , doubleTyID , int64TyID , uint64TyID ,
functionTyID , none
}
TypeID enum.
Functions
Expected< Function * > getFunction (std::string Name, Context &m_context, LocalContext &m_local_context)
AllocaInst * CreateEntryBlockAlloca (Function *TheFunction, const StringRef VarName, Type *var_type, Context &m_context, LocalContext &m_local_context)
AllocaInst * CreateEntryBlockAlloca (Function *TheFunction, const StringRef VarName, TypeID VarType, Context &m_context, LocalContext &m_local_context)
void init__ ()
void CreateExplictCast (Value *&val, TypeID fromTy, TypeID toTy, LocalContext &ctx)
Creates explict cast.
TypeID CreateImplictCast (Value *&lhs, Value *&rhs, TypeID lhsTy, TypeID rhsTy, LocalContext &ctx)
Creates implict cast.
Value * CtreateCMP (CmpPredicate pred, Value *lhs, Value *rhs, TypeID type_, LocalContext &ctx, const llvm::Twine &Name="")
Value * CreateAdd (Value *lhs, Value *rhs, TypeID type_, LocalContext &ctx, const llvm::Twine &Name="")
Value * CreateSub (Value *lhs, Value *rhs, TypeID type_, LocalContext &ctx, const llvm::Twine &Name="")
Value * CreateMul (Value *lhs, Value *rhs, TypeID type_, LocalContext &ctx, const llvm::Twine &Name="")
Value * CreateDiv (Value *lhs, Value *rhs, TypeID type_, LocalContext &ctx, const llvm::Twine &Name="")
llvm::Type * get_llvm_type (TypeID TyID, LocalContext &m_local_context)
Translates TypeID types to llvm types.
TypeID operator+ (TypeID lhs, TypeID rhs)
bool isFloatingPointTy (TypeID type_)
Checks if value type is floating point type.
bool isIntegerTy (TypeID type_)
Checks if value type is integer type.
bool isSigned (TypeID type_)
Variables
const set< string > special_literals = {"true", "false"}
Enumeration Type Documentation
CmpPredicate
enum slljit::CmpPredicate
CmpPredicate enum.
Defines predicates for comparison operation
Enumerator
equal
not_equal
greater_than
greater_or_equal
less_then
less_or_equal
LayoutVarTypes
enum slljit::LayoutVarTypes
Enumerator
Kdouble
Kint64
Kuint64
Token
enum slljit::Token : int
Token enum.
Token representation. All values < 0.
Enumerator
tok_eof
wnd of file token
tok_type
type token
tok_extern
extern token
tok_identifier
inedtifier token
tok_literal
literal value token
tok_if
'if' control command token
tok_else
'else' control command token
tok_for
'for' control command token
TypeID
enum slljit::TypeID
TypeID enum.
Represents value types.
Enumerator
boolTyID
boolean int1 unsigned
doubleTyID
double 64 bit wide
int64TyID
signed int64
uint64TyID
unsigned int64
functionTyID
Represents function
none
untyped value. Not synonymous to void.
Function Documentation
CreateAdd()
Value * slljit::CreateAdd (Value * lhs, Value * rhs, TypeID type_, LocalContext & ctx, const llvm::Twine & Name = "")
Creates CMP instruction. Requires both operands to be of the same type.
References slljit::LocalContext::getBuilder(), isFloatingPointTy(), and isIntegerTy().
CreateDiv()
Value * slljit::CreateDiv (Value * lhs, Value * rhs, TypeID type_, LocalContext & ctx, const llvm::Twine & Name = "")
Creates Div instruction. Requires both operands to be of the same type.
References slljit::LocalContext::getBuilder(), isFloatingPointTy(), isIntegerTy(), and isSigned().
CreateEntryBlockAlloca()
AllocaInst * slljit::CreateEntryBlockAlloca (Function * TheFunction, const StringRef VarName, Type * var_type, Context & m_context, LocalContext & m_local_context)
CreateExplictCast()
void slljit::CreateExplictCast (Value *& val, TypeID fromTy, TypeID toTy, LocalContext & ctx)
Creates explict cast.
References get_llvm_type(), slljit::LocalContext::getBuilder(), isFloatingPointTy(), isIntegerTy(), and isSigned().
CreateImplictCast()
TypeID slljit::CreateImplictCast (Value *& lhs, Value *& rhs, TypeID lhsTy, TypeID rhsTy, LocalContext & ctx)
Creates implict cast.
References CreateExplictCast().
CreateMul()
Value * slljit::CreateMul (Value * lhs, Value * rhs, TypeID type_, LocalContext & ctx, const llvm::Twine & Name = "")
Creates Mul instruction. Requires both operands to be of the same type.
References slljit::LocalContext::getBuilder(), isFloatingPointTy(), and isIntegerTy().
CreateSub()
Value * slljit::CreateSub (Value * lhs, Value * rhs, TypeID type_, LocalContext & ctx, const llvm::Twine & Name = "")
Creates Sub instruction. Requires both operands to be of the same type.
References slljit::LocalContext::getBuilder(), isFloatingPointTy(), and isIntegerTy().
CtreateCMP()
Value * slljit::CtreateCMP (CmpPredicate pred, Value * lhs, Value * rhs, TypeID type_, LocalContext & ctx, const llvm::Twine & Name = "")
Creates CMP instruction. Requires both operands to be of the same type.
References slljit::LocalContext::getBuilder().
get_llvm_type()
llvm::Type * slljit::get_llvm_type (TypeID TyID, LocalContext & m_local_context)
Translates TypeID types to llvm types.
References boolTyID, doubleTyID, functionTyID, slljit::LocalContext::getBuilder(), int64TyID, none, and uint64TyID.
init__()
static void slljit::init__ ()
isFloatingPointTy()
bool slljit::isFloatingPointTy (TypeID type_)
Checks if value type is floating point type.
References doubleTyID.
isIntegerTy()
bool slljit::isIntegerTy (TypeID type_)
Checks if value type is integer type.
References boolTyID, int64TyID, and uint64TyID.
isSigned()
bool slljit::isSigned (TypeID type_)
Checks if value type is signed. Requires type to be integer.
References int64TyID.
operator+()
TypeID slljit::operator+ (TypeID lhs, TypeID rhs)
Used for implict casting.
Returns
Resulting type for any operation perormed on given types.
Variable Documentation
special_literals
const set<string> slljit::special_literals = {"true", "false"}